name: pikkar
description: "Pikkar is a delivery app that allows you to order food and get it delivered to your door."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# ðŸ”´ THIS MUST BE OUTSIDE flutter:
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo_red.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/